#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-gdal-soname27
Version  : 3.1.2
Release  : 46
URL      : https://download.osgeo.org/gdal/3.1.2/gdal-3.1.2.tar.xz
Source0  : https://download.osgeo.org/gdal/3.1.2/gdal-3.1.2.tar.xz
Summary  : Geospatial Data Abstraction Library
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause ISC LGPL-2.0 Libpng MIT Qhull
Requires: compat-gdal-soname27-lib = %{version}-%{release}
Requires: compat-gdal-soname27-license = %{version}-%{release}
BuildRequires : SFCGAL-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-cpan
BuildRequires : buildreq-distutils3
BuildRequires : curl-dev
BuildRequires : expat-dev
BuildRequires : geos-dev
BuildRequires : gettext-bin
BuildRequires : giflib-dev
BuildRequires : hdf5-dev
BuildRequires : json-c-dev
BuildRequires : libgeotiff-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libwebp-dev
BuildRequires : m4
BuildRequires : ocl-icd-dev
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(OpenEXR)
BuildRequires : pkgconfig(libpq)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(spatialite)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : proj
BuildRequires : proj-dev
BuildRequires : qhull-dev
BuildRequires : tiff-dev
BuildRequires : unixODBC-dev
BuildRequires : xerces-c-dev
BuildRequires : zstd-dev
Patch1: 0001-Fix-compilation-error-on-json-c-external-link.patch
Patch2: 0002-Add-some-missing-limits-includes.patch
Patch3: 0003-EXR-fix-build-against-OpenEXR-3.0.1-fixes-3770.patch
Patch4: 0004-Workaround-for-inability-to-run-autoreconf.patch
Patch5: 0005-Fix-configure-check-for-openexr-3.patch
Patch6: 0006-Unix-build-fix-detection-of-minor-version-number-of-.patch

%description
Use this script to create a valid "ogrsosidatatypes.h" include file based on the element definitions in the standard. You can extract the XML files by exporting the tables of the same name from the official Access-Database at

%package lib
Summary: lib components for the compat-gdal-soname27 package.
Group: Libraries
Requires: compat-gdal-soname27-license = %{version}-%{release}

%description lib
lib components for the compat-gdal-soname27 package.


%package license
Summary: license components for the compat-gdal-soname27 package.
Group: Default

%description license
license components for the compat-gdal-soname27 package.


%prep
%setup -q -n gdal-3.1.2
cd %{_builddir}/gdal-3.1.2
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
## build_prepend content
sed -i 's/-flto"$/-flto=auto"/' ./configure.ac
# Also patch the generated configure script, in case we stop patching
# configure.ac, m4 files, etc.
sed -i 's/-flto"$/-flto=auto"/' ./configure
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664890677
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
%reconfigure --disable-static --with-libtiff=yes \
--with-png=yes \
--with-spatialite=yes \
--with-sqlite3=yes \
--with-poppler=no \
--enable-lto \
--with-gif=/usr \
--with-libjson-c=/usr \
--with-libtool=yes
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1664890677
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-gdal-soname27
cp %{_builddir}/gdal-%{version}/LICENSE.TXT %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/3c5056c99522acf3d9e2c2a2f61fdeeffced4174 || :
cp %{_builddir}/gdal-%{version}/alg/internal_libqhull/COPYING.txt %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/baf1d15dcf66b1e1dfee80eb405aa73105842017 || :
cp %{_builddir}/gdal-%{version}/doc/source/gdal_rtd/LICENSE %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/8ce271d47d282a4da574b385a8aff7a0d735188e || :
cp %{_builddir}/gdal-%{version}/doc/source/license.rst %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/0f9d62383e84298877fe5f5d41f6a944f7ef8563 || :
cp %{_builddir}/gdal-%{version}/frmts/gif/giflib/COPYING %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/f9c9a2d3495a0766b4cf20d4b90cfe714dab3dc1 || :
cp %{_builddir}/gdal-%{version}/frmts/mrf/libLERC/LICENSE.TXT %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/3035b519169390d1aaa3a43267deaae5cdff8a9b || :
cp %{_builddir}/gdal-%{version}/frmts/pcraster/libcsf/COPYING %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/1d982db70b88f943cc7d15013c28a126339d6cbc || :
cp %{_builddir}/gdal-%{version}/frmts/png/libpng/LICENSE %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/fc3951ba26fe1914759f605696a1d23e3b41766f || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/flatgeobuf/LICENSE %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/161732baff9a38188301a521b567a20245367c7e || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/LICENSE %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/abb8eb20f7f319cd8b292cdccce15826bac01363 || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/geojson/libjson/COPYING %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/0cd23537e3c32497c7b87157b36f9d2eb5fca64b || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/shape/COPYING %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/df97bdf33b01f9ed42a799dd3ed7a1599dd0cb9d || :
cp %{_builddir}/gdal-%{version}/port/LICENCE_minizip %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/f7f1d88d0aea6c567a2c351b08b0fe80f2582054 || :
cp %{_builddir}/gdal-%{version}/third_party/LercLib/LICENSE %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/3035b519169390d1aaa3a43267deaae5cdff8a9b || :
cp %{_builddir}/gdal-%{version}/third_party/LercLib/NOTICE %{buildroot}/usr/share/package-licenses/compat-gdal-soname27/4e8e03579f57bab9de5401be3fb96344f0823ead || :
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/etc/bash_completion.d/gdal-bash-completion.sh
rm -f %{buildroot}*/usr/bin/gdal-config
rm -f %{buildroot}*/usr/bin/gdal_contour
rm -f %{buildroot}*/usr/bin/gdal_grid
rm -f %{buildroot}*/usr/bin/gdal_rasterize
rm -f %{buildroot}*/usr/bin/gdal_translate
rm -f %{buildroot}*/usr/bin/gdal_viewshed
rm -f %{buildroot}*/usr/bin/gdaladdo
rm -f %{buildroot}*/usr/bin/gdalbuildvrt
rm -f %{buildroot}*/usr/bin/gdaldem
rm -f %{buildroot}*/usr/bin/gdalenhance
rm -f %{buildroot}*/usr/bin/gdalinfo
rm -f %{buildroot}*/usr/bin/gdallocationinfo
rm -f %{buildroot}*/usr/bin/gdalmanage
rm -f %{buildroot}*/usr/bin/gdalmdiminfo
rm -f %{buildroot}*/usr/bin/gdalmdimtranslate
rm -f %{buildroot}*/usr/bin/gdalserver
rm -f %{buildroot}*/usr/bin/gdalsrsinfo
rm -f %{buildroot}*/usr/bin/gdaltindex
rm -f %{buildroot}*/usr/bin/gdaltransform
rm -f %{buildroot}*/usr/bin/gdalwarp
rm -f %{buildroot}*/usr/bin/gnmanalyse
rm -f %{buildroot}*/usr/bin/gnmmanage
rm -f %{buildroot}*/usr/bin/nearblack
rm -f %{buildroot}*/usr/bin/ogr2ogr
rm -f %{buildroot}*/usr/bin/ogrinfo
rm -f %{buildroot}*/usr/bin/ogrlineref
rm -f %{buildroot}*/usr/bin/ogrtindex
rm -f %{buildroot}*/usr/bin/testepsg
rm -f %{buildroot}*/usr/include/cpl_atomic_ops.h
rm -f %{buildroot}*/usr/include/cpl_auto_close.h
rm -f %{buildroot}*/usr/include/cpl_config.h
rm -f %{buildroot}*/usr/include/cpl_config_extras.h
rm -f %{buildroot}*/usr/include/cpl_conv.h
rm -f %{buildroot}*/usr/include/cpl_csv.h
rm -f %{buildroot}*/usr/include/cpl_error.h
rm -f %{buildroot}*/usr/include/cpl_hash_set.h
rm -f %{buildroot}*/usr/include/cpl_http.h
rm -f %{buildroot}*/usr/include/cpl_json.h
rm -f %{buildroot}*/usr/include/cpl_list.h
rm -f %{buildroot}*/usr/include/cpl_minixml.h
rm -f %{buildroot}*/usr/include/cpl_minizip_ioapi.h
rm -f %{buildroot}*/usr/include/cpl_minizip_unzip.h
rm -f %{buildroot}*/usr/include/cpl_minizip_zip.h
rm -f %{buildroot}*/usr/include/cpl_multiproc.h
rm -f %{buildroot}*/usr/include/cpl_odbc.h
rm -f %{buildroot}*/usr/include/cpl_port.h
rm -f %{buildroot}*/usr/include/cpl_progress.h
rm -f %{buildroot}*/usr/include/cpl_quad_tree.h
rm -f %{buildroot}*/usr/include/cpl_spawn.h
rm -f %{buildroot}*/usr/include/cpl_string.h
rm -f %{buildroot}*/usr/include/cpl_time.h
rm -f %{buildroot}*/usr/include/cpl_virtualmem.h
rm -f %{buildroot}*/usr/include/cpl_vsi.h
rm -f %{buildroot}*/usr/include/cpl_vsi_error.h
rm -f %{buildroot}*/usr/include/cpl_vsi_virtual.h
rm -f %{buildroot}*/usr/include/cplkeywordparser.h
rm -f %{buildroot}*/usr/include/gdal.h
rm -f %{buildroot}*/usr/include/gdal_alg.h
rm -f %{buildroot}*/usr/include/gdal_alg_priv.h
rm -f %{buildroot}*/usr/include/gdal_csv.h
rm -f %{buildroot}*/usr/include/gdal_frmts.h
rm -f %{buildroot}*/usr/include/gdal_mdreader.h
rm -f %{buildroot}*/usr/include/gdal_pam.h
rm -f %{buildroot}*/usr/include/gdal_priv.h
rm -f %{buildroot}*/usr/include/gdal_proxy.h
rm -f %{buildroot}*/usr/include/gdal_rat.h
rm -f %{buildroot}*/usr/include/gdal_simplesurf.h
rm -f %{buildroot}*/usr/include/gdal_utils.h
rm -f %{buildroot}*/usr/include/gdal_version.h
rm -f %{buildroot}*/usr/include/gdal_vrt.h
rm -f %{buildroot}*/usr/include/gdalgeorefpamdataset.h
rm -f %{buildroot}*/usr/include/gdalgrid.h
rm -f %{buildroot}*/usr/include/gdalgrid_priv.h
rm -f %{buildroot}*/usr/include/gdaljp2abstractdataset.h
rm -f %{buildroot}*/usr/include/gdaljp2metadata.h
rm -f %{buildroot}*/usr/include/gdalpansharpen.h
rm -f %{buildroot}*/usr/include/gdalwarper.h
rm -f %{buildroot}*/usr/include/gnm.h
rm -f %{buildroot}*/usr/include/gnm_api.h
rm -f %{buildroot}*/usr/include/gnmgraph.h
rm -f %{buildroot}*/usr/include/memdataset.h
rm -f %{buildroot}*/usr/include/ogr_api.h
rm -f %{buildroot}*/usr/include/ogr_core.h
rm -f %{buildroot}*/usr/include/ogr_feature.h
rm -f %{buildroot}*/usr/include/ogr_featurestyle.h
rm -f %{buildroot}*/usr/include/ogr_geocoding.h
rm -f %{buildroot}*/usr/include/ogr_geometry.h
rm -f %{buildroot}*/usr/include/ogr_p.h
rm -f %{buildroot}*/usr/include/ogr_spatialref.h
rm -f %{buildroot}*/usr/include/ogr_srs_api.h
rm -f %{buildroot}*/usr/include/ogr_swq.h
rm -f %{buildroot}*/usr/include/ogrsf_frmts.h
rm -f %{buildroot}*/usr/include/rawdataset.h
rm -f %{buildroot}*/usr/include/vrtdataset.h
rm -f %{buildroot}*/usr/lib64/libgdal.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/gdal.pc
rm -f %{buildroot}*/usr/share/gdal/GDALLogoBW.svg
rm -f %{buildroot}*/usr/share/gdal/GDALLogoColor.svg
rm -f %{buildroot}*/usr/share/gdal/GDALLogoGS.svg
rm -f %{buildroot}*/usr/share/gdal/LICENSE.TXT
rm -f %{buildroot}*/usr/share/gdal/bag_template.xml
rm -f %{buildroot}*/usr/share/gdal/cubewerx_extra.wkt
rm -f %{buildroot}*/usr/share/gdal/default.rsc
rm -f %{buildroot}*/usr/share/gdal/ecw_cs.wkt
rm -f %{buildroot}*/usr/share/gdal/eedaconf.json
rm -f %{buildroot}*/usr/share/gdal/epsg.wkt
rm -f %{buildroot}*/usr/share/gdal/esri_StatePlane_extra.wkt
rm -f %{buildroot}*/usr/share/gdal/gdalicon.png
rm -f %{buildroot}*/usr/share/gdal/gdalmdiminfo_output.schema.json
rm -f %{buildroot}*/usr/share/gdal/gdalvrt.xsd
rm -f %{buildroot}*/usr/share/gdal/gml_registry.xml
rm -f %{buildroot}*/usr/share/gdal/gmlasconf.xml
rm -f %{buildroot}*/usr/share/gdal/gmlasconf.xsd
rm -f %{buildroot}*/usr/share/gdal/gt_datum.csv
rm -f %{buildroot}*/usr/share/gdal/gt_ellips.csv
rm -f %{buildroot}*/usr/share/gdal/header.dxf
rm -f %{buildroot}*/usr/share/gdal/inspire_cp_BasicPropertyUnit.gfs
rm -f %{buildroot}*/usr/share/gdal/inspire_cp_CadastralBoundary.gfs
rm -f %{buildroot}*/usr/share/gdal/inspire_cp_CadastralParcel.gfs
rm -f %{buildroot}*/usr/share/gdal/inspire_cp_CadastralZoning.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_AdmArea.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_AdmBdry.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_AdmPt.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_BldA.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_BldL.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_Cntr.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_CommBdry.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_CommPt.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_Cstline.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_ElevPt.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_GCP.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_LeveeEdge.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RailCL.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RdASL.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RdArea.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RdCompt.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RdEdg.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RdMgtBdry.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RdSgmtA.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_RvrMgtBdry.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_SBAPt.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_SBArea.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_SBBdry.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_WA.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_WL.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_WStrA.gfs
rm -f %{buildroot}*/usr/share/gdal/jpfgdgml_WStrL.gfs
rm -f %{buildroot}*/usr/share/gdal/netcdf_config.xsd
rm -f %{buildroot}*/usr/share/gdal/nitf_spec.xml
rm -f %{buildroot}*/usr/share/gdal/nitf_spec.xsd
rm -f %{buildroot}*/usr/share/gdal/ogrvrt.xsd
rm -f %{buildroot}*/usr/share/gdal/osmconf.ini
rm -f %{buildroot}*/usr/share/gdal/ozi_datum.csv
rm -f %{buildroot}*/usr/share/gdal/ozi_ellips.csv
rm -f %{buildroot}*/usr/share/gdal/pci_datum.txt
rm -f %{buildroot}*/usr/share/gdal/pci_ellips.txt
rm -f %{buildroot}*/usr/share/gdal/pdfcomposition.xsd
rm -f %{buildroot}*/usr/share/gdal/pds4_template.xml
rm -f %{buildroot}*/usr/share/gdal/plscenesconf.json
rm -f %{buildroot}*/usr/share/gdal/ruian_vf_ob_v1.gfs
rm -f %{buildroot}*/usr/share/gdal/ruian_vf_st_uvoh_v1.gfs
rm -f %{buildroot}*/usr/share/gdal/ruian_vf_st_v1.gfs
rm -f %{buildroot}*/usr/share/gdal/ruian_vf_v1.gfs
rm -f %{buildroot}*/usr/share/gdal/s57agencies.csv
rm -f %{buildroot}*/usr/share/gdal/s57attributes.csv
rm -f %{buildroot}*/usr/share/gdal/s57expectedinput.csv
rm -f %{buildroot}*/usr/share/gdal/s57objectclasses.csv
rm -f %{buildroot}*/usr/share/gdal/seed_2d.dgn
rm -f %{buildroot}*/usr/share/gdal/seed_3d.dgn
rm -f %{buildroot}*/usr/share/gdal/stateplane.csv
rm -f %{buildroot}*/usr/share/gdal/trailer.dxf
rm -f %{buildroot}*/usr/share/gdal/vdv452.xml
rm -f %{buildroot}*/usr/share/gdal/vdv452.xsd
rm -f %{buildroot}*/usr/share/gdal/vicar.json
## install_append content
#install -D %{buildroot}/usr/etc/bash_completion.d/gdal-bash-completion.sh %{buildroot}/usr/share/bash-completion/completions/gdal-bash-completion.sh
## install_append end

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgdal.so.27
/usr/lib64/libgdal.so.27.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-gdal-soname27/0cd23537e3c32497c7b87157b36f9d2eb5fca64b
/usr/share/package-licenses/compat-gdal-soname27/0f9d62383e84298877fe5f5d41f6a944f7ef8563
/usr/share/package-licenses/compat-gdal-soname27/161732baff9a38188301a521b567a20245367c7e
/usr/share/package-licenses/compat-gdal-soname27/1d982db70b88f943cc7d15013c28a126339d6cbc
/usr/share/package-licenses/compat-gdal-soname27/3035b519169390d1aaa3a43267deaae5cdff8a9b
/usr/share/package-licenses/compat-gdal-soname27/3c5056c99522acf3d9e2c2a2f61fdeeffced4174
/usr/share/package-licenses/compat-gdal-soname27/4e8e03579f57bab9de5401be3fb96344f0823ead
/usr/share/package-licenses/compat-gdal-soname27/8ce271d47d282a4da574b385a8aff7a0d735188e
/usr/share/package-licenses/compat-gdal-soname27/abb8eb20f7f319cd8b292cdccce15826bac01363
/usr/share/package-licenses/compat-gdal-soname27/baf1d15dcf66b1e1dfee80eb405aa73105842017
/usr/share/package-licenses/compat-gdal-soname27/df97bdf33b01f9ed42a799dd3ed7a1599dd0cb9d
/usr/share/package-licenses/compat-gdal-soname27/f7f1d88d0aea6c567a2c351b08b0fe80f2582054
/usr/share/package-licenses/compat-gdal-soname27/f9c9a2d3495a0766b4cf20d4b90cfe714dab3dc1
/usr/share/package-licenses/compat-gdal-soname27/fc3951ba26fe1914759f605696a1d23e3b41766f
